#image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest
image: docker:20-git

stages: # List of stages for jobs, and their order of execution
  - test        
  - build-docker
  - build-firmware

services:
  - docker:dind

variables:
  LEDGER_BUILDER_IMAGE: registry.gitlab.com/accumulatenetwork/ledger/app-accumulate
  APP_VERSION: "1.0.2"
  BOLD_RED: '\e[1;31m'
  NO_COLOR: '\e[0m'
  SECTION: '\e[0K'

.rules all:
  rules:
  - if: $CI_PIPELINE_SOURCE != ''

lint:
  stage: test
  before_script:
    - function die { echo -e "${BOLD_RED}${1}${NO_COLOR}"; false; }
  script:
    - apt-get -y update && apt-get -y install clang-format 
    - echo -e "${SECTION}section_start:`date +%s`:generate\r${SECTION}Verify code is correctly formatted"
    - find src/ -type f \( -name "*.h" -o -name "*.c" \) -exec clang-format -i {} \;
    - git diff --quiet || die "Please run clang-format on the following files\n$(git ls-files -m)"
    - echo -e "${SECTION}section_end:`date +%s`:generate\r${SECTION}"

build docker image:
  stage: build-docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${LEDGER_BUILDER_IMAGE} .
    - docker push ${LEDGER_BUILDER_IMAGE}

build-nano-s:
  stage: build-firmware
  image: ${LEDGER_BUILDER_IMAGE}
  variables:
    BOLOS_SDK: /opt/nanos-secure-sdk
    OUTPUT_PKG_NAME: app-accumulate-nano-s
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nano-s"
  before_script:
    - function die { echo -e "${BOLD_RED}${1}${NO_COLOR}"; false; }
  script:
    - if [[ -z "${OUTPUT_PKG_NAME}" ]]; then OUTPUT_PKG_NAME="app-accumulate"; fi
    - cd /app
    - rm -rf bin obj debug dep output-scan-build dist
    - mkdir -p dist
    - make clean; make scan-build
    - [ "$(ls -A output-scan-build)" ] && zip -r dist/output-scan-build.zip output-scan-build/* && die "static analysis scan detected errors"
    - cp bin/app.elf "dist/${OUTPUT_PKG_NAME}.elf"
    - cp bin/app.sha256 "dist/${OUTPUT_PKG_NAME}.sha256"
    - cp bin/app.hex "dist/${OUTPUT_PKG_NAME}.hex"
    - cp bin/app.apdu "dist/${OUTPUT_PKG_NAME}.apdu"

build-nano-splus:
  stage: build-firmware
  image: ${LEDGER_BUILDER_IMAGE}
  variables:
    BOLOS_SDK: /opt/nanosplus-secure-sdk
    OUTPUT_PKG_NAME: app-accumulate-nano-splus
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nano-splus"
  before_script:
    - function die { echo -e "${BOLD_RED}${1}${NO_COLOR}"; false; }
  script:
    - if [[ -z "${OUTPUT_PKG_NAME}" ]]; then OUTPUT_PKG_NAME="app-accumulate"; fi
    - cd /app
    - rm -rf bin obj debug dep output-scan-build dist
    - mkdir -p dist
    - make clean; make scan-build
    - [ "$(ls -A output-scan-build)" ] && zip -r dist/output-scan-build.zip output-scan-build/* && die "static analysis scan detected errors"
    - cp bin/app.elf "dist/${OUTPUT_PKG_NAME}.elf"
    - cp bin/app.sha256 "dist/${OUTPUT_PKG_NAME}.sha256"
    - cp bin/app.hex "dist/${OUTPUT_PKG_NAME}.hex"
    - cp bin/app.apdu "dist/${OUTPUT_PKG_NAME}.apdu"
    #- docker run --rm -e BOLOS_SDK="${BOLOS_SDK}" -e OUTPUT_PKG_NAME="${OUTPUT_PKG_NAME}" -e CI_JOB_TOKEN="${CI_JOB_TOKEN}" -e APP_VERSION="${APP_VERSION}" -e PACKAGE_REGISTRY_URL=${PACKAGE_REGISTRY_URL} ${LEDGER_BUILDER_IMAGE}

build-nano-x:
  stage: build-firmware
  image: ${LEDGER_BUILDER_IMAGE}
  variables:
    BOLOS_SDK: /opt/nanox-secure-sdk
    OUTPUT_PKG_NAME: app-accumulate-nano-x
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/nano-x"
  before_script:
    - function die { echo -e "${BOLD_RED}${1}${NO_COLOR}"; false; }
  script:
    - if [[ -z "${OUTPUT_PKG_NAME}" ]]; then OUTPUT_PKG_NAME="app-accumulate"; fi
    - cd /app
    - rm -rf bin obj debug dep output-scan-build dist
    - mkdir -p dist
    - make clean; make scan-build
    - [ "$(ls -A output-scan-build)" ] && zip -r dist/output-scan-build.zip output-scan-build/* && die "static analysis scan detected errors"
    - cp bin/app.elf "dist/${OUTPUT_PKG_NAME}.elf"
    - cp bin/app.sha256 "dist/${OUTPUT_PKG_NAME}.sha256"
    - cp bin/app.hex "dist/${OUTPUT_PKG_NAME}.hex"
    - cp bin/app.apdu "dist/${OUTPUT_PKG_NAME}.apdu"
    #- docker run --rm -e BOLOS_SDK="${BOLOS_SDK}" -e OUTPUT_PKG_NAME="${OUTPUT_PKG_NAME}" -e CI_JOB_TOKEN="${CI_JOB_TOKEN}" -e APP_VERSION="${APP_VERSION}" -e PACKAGE_REGISTRY_URL=${PACKAGE_REGISTRY_URL} ${LEDGER_BUILDER_IMAGE}
