/*****************************************************************************
*   Accumulate Ledger Wallet
*   (c) 2022 DefiDevs, Inc.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*****************************************************************************/

#include <stdint.h>  // uint*_t
#include <string.h>
#include "debug_tx.h"
#include "constants.h"
#include "globals.h"
#include "io.h"
#include "sw.h"
#include "types.h"
#include "common/buffer.h"
#include "ui/display/display.h"
#include "ux.h"
#include "os.h"
#include "common/protocol/signatures.h"
#include "ui/dynamic_display.h"


int handler_debug_tx() {
#ifdef DEBUG_SEND_TOKENS
    PRINTF("checkpoint A\n");
    //const char *apdu_payload = "008b01020220e55d973bf691381c94602354d1e1f655f7b1c4bd56760dffeffa2bef4541ec11043b6163633a2f2f6336613632396639613635626632313135396335646662666662633836386563336165363163653436353131303865632f41434d450501069ca3e4b4ba3008c4dcfc1b86ccdd0cd7937fcb2619a2735b59f8119a43cd7d396690b5c017bf0400b6016b013b6163633a2f2f6336613632396639613635626632313135396335646662666662633836386563336165363163653436353131303865632f41434d45022aa4dd0e234834061b2ec1402b95e7888af941f6d47d3a5d82e15789c47c82c9030b6c65646765722074657374024701030443013b6163633a2f2f6639666562393361313063616632646466313633396336666634353934666262313939633964653963643130636134372f41434d4502043b9aca002036fbe60414509eb11b04b900d8d69191e456fac7b33a74842af7272968c308e5";
    //uint8_t raw_tx[1024] = {0};
    //hextobin(apdu_payload, strlen(apdu_payload), G_context.tx_info.raw_tx, sizeof(G_context.tx_info.raw_tx));
    G_context.tx_info.raw_tx_len = 0;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x0;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x20;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x5d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x97;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x91;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1c;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x94;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x60;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x23;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x54;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf6;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x55;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xbd;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x56;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x76;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xff;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xef;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xfa;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xef;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x45;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x41;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xec;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x11;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x33;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x41;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x43;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x45;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x9c;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xa3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xba;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xdc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xfc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x86;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xcc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xdd;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x93;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x7f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xcb;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x26;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x19;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xa2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x73;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x5b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x59;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf8;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x11;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x9a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x43;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xcd;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x7d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x90;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc0;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x17;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xbf;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x0;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x33;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x41;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x43;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x45;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xa4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xdd;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x23;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x48;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2e;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x40;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x95;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x88;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf9;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x41;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x7d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x5d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x82;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x57;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x89;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x7c;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x82;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc9;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6c;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x67;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x72;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x20;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x74;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x73;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x74;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x47;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x43;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x33;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x33;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x37;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x41;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x43;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x45;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x9a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xca;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x0;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x20;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xfb;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x14;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x50;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x9e;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb9;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x0;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd8;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x91;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x91;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x56;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xfa;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x74;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x84;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x27;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x29;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x68;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe5;

    PRINTF("checkpoint B\n");
    int e = parse_transaction(G_context.tx_info.raw_tx, G_context.tx_info.raw_tx_len,
                             &G_context.tx_info.signer, &G_context.tx_info.transaction);
    if (IsError(ErrorCode(e))) {
        return io_send_sw(SW_ENCODE_ERROR(ErrorCode(e)));
    }

    PRINTF("checkpoint Tango\n");
#endif
#ifdef DEBUG_ADD_CREDITS
    G_context.tx_info.raw_tx_len = 0;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x0;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x20;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x5d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x97;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x91;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1c;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x94;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x60;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x23;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x54;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf6;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x55;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xbd;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x56;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x76;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xff;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xef;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xfa;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xef;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x45;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x41;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xec;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x11;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x33;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x41;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x43;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x45;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xa7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc9;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xbe;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xbc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x83;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x22;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x90;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc8;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x15;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xa3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb8;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8a;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xae;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8c;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd0;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x52;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xcf;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x86;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3e;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x9d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd8;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x54;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x59;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3e;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x0;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x33;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x38;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x41;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x43;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x45;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x69;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xcc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xdd;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x24;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6e;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x91;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xde;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3e;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x5f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf6;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x93;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x42;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xcc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xea;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x29;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xac;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x23;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xb;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6c;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x67;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x72;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x20;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x74;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x73;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x74;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x48;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3a;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x33;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x32;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x33;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x36;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x35;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x66;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x62;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x65;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x39;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x64;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x31;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x30;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x63;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x34;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x37;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x41;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x43;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x45;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x3b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x9a;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xca;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x0;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd2;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x9;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x20;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x26;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x33;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x79;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xa1;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x8b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xef;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xfc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xa7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x85;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x9b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xfb;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x2b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xee;
    G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6d;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd5;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xd4;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x1b;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xa9;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x91;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe0;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x76;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x14;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x4e;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xe;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xf7;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xc;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x6f;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0x61;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xde;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xa0;  G_context.tx_info.raw_tx[G_context.tx_info.raw_tx_len++] = 0xba;  //359

    int e = parse_transaction(G_context.tx_info.raw_tx, G_context.tx_info.raw_tx_len,
                              &G_context.tx_info.signer, &G_context.tx_info.transaction);
    if (IsError(ErrorCode(e))) {
        return io_send_sw(SW_ENCODE_ERROR(ErrorCode(e)));
    }

#endif
    debug_display();
    //    ui_display_transaction(&G_context.tx_info.signer, &G_context.tx_info.transaction);
    return io_send_sw(SW_OK);
}
