#pragma once
/// GENERATED BY go run ./tools/cmd/gen-types. DO NOT EDIT.

#include <encoding/encoding.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef ACME_STATIC
#define ACME_API static
#else
#define ACME_API extern
#endif

#ifndef _WANT_Envelope_
#define _WANT_Envelope_ 1
#endif

/// Forward Declarations
struct Envelope;

/// Data Structures
#if _WANT_Envelope_
typedef struct Envelope {
    size_t Signatures_length;
    Signature* Signatures;  //`json:"signatures,omitempty" form:"signatures" query:"signatures"
                            // validate:"required"`
    Bytes TxHash;           //`json:"txHash,omitempty" form:"txHash" query:"txHash"`
    size_t Transaction_length;
    Transaction*
        Transaction;  //`json:"transaction,omitempty" form:"transaction" query:"transaction"`
    Bytes extraData[3];
} Envelope;

ACME_API int readEnvelope(Unmarshaler* m, Envelope* v);

#endif /* _WANT_Envelope_ */

#ifdef __cplusplus
}
#endif
